# Generated by Django 2.1.5 on 2019-02-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190221_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='user_like',
            new_name='users_like',
        ),
    ]
